<?php

/**
 * @file
 *
 * This module implements UI elements for Janrain Capture
 *
 * @see http://www.janrain.com/products/capture
 */

function _janrain_capture_ui_init_dependencies($variables) {
  $scripts[] = !empty($variables['janrain_capture_dependencies']['capture_json2'])
    ? $variables['janrain_capture_dependencies']['capture_json2']
    : 'sites/all/libraries/json2/json2.js';
  $scripts[] = !empty($variables['janrain_capture_dependencies']['capture_fancy_js'])
    ? $variables['janrain_capture_dependencies']['capture_fancy_js']
    : 'sites/all/libraries/fancybox/jquery.fancybox-1.3.4.pack.js';

  foreach ($scripts as $value) {
    drupal_add_js($value);
  }
}

/**
 * Implements hook_init().
 */
function janrain_capture_ui_init() {
  global $user;

  $module_path = drupal_get_path('module', 'janrain_capture_ui') . DIRECTORY_SEPARATOR;

  $variables = array(
    'janrain_capture_main' => variable_get('janrain_capture_main', array()),
    'janrain_capture_optional' => variable_get('janrain_capture_optional', array()),
    'janrain_capture_dependencies' => variable_get('janrain_capture_dependencies', array()),
  );

  _janrain_capture_ui_init_dependencies($variables);

  $variables['capture_sso_address'] = !empty($variables['janrain_capture_optional']['capture_sso_address'])
    ? $variables['janrain_capture_optional']['capture_sso_address'] : '';
  $variables['capture_client_id'] = !empty($variables['janrain_capture_main']['capture_client_id'])
    ? $variables['janrain_capture_main']['capture_client_id'] : '';

  $scripts = array('module' => array(), 'inline' => array());

  $path = isset($_GET['q']) ? $_GET['q'] : '<front>';
  $link = url($path, array('absolute' => TRUE));
  $uri_opts = array('query' => array('origin' => urlencode($link)), 'absolute' => TRUE);

  $scripts['inline'][] = 'jQuery(function($) {
  $(".fancy").fancybox({
    padding: 0,
    scrolling: "no",
    autoScale: true,
    width: 666,
    autoDimensions: false
  });
});';

  $styles = array();
  $styles[] = !empty($janrain_capture_dependencies['capture_fancy_css'])
    ? $janrain_capture_dependencies['capture_fancy_css']
    : 'sites/all/libraries/fancybox/jquery.fancybox-1.3.4.css';

  if (!empty($capture_sso_address)) {
    $scripts['inline'][] = 'JANRAIN.SSO.CAPTURE.check_login({
  sso_server: "https://' . $capture_sso_address . '",
  client_id: "' . $capture_client_id . '",
  redirect_uri: "' . url('janrain_capture/oauth', array('query' => array('from_sso' => 'true'), 'absolute' => TRUE)) . '",
  logout_uri: "' . url('user/logout', array('absolute' => TRUE)) . '",
  xd_receiver: "' . url(NULL, array('absolute' => TRUE)) . drupal_get_path('module', 'janrain_capture') . '/xdcomm.html"
});
function janrain_capture_logout() {
  JANRAIN.SSO.CAPTURE.logout({
    sso_server: "https://' . $capture_sso_address . '",
    logout_uri: "' . url('user/logout', array('absolute' => TRUE)) . '"
  });
}
jQuery(function($) {
    $(".menu li a[href=\'' . url('user/logout') . '\']").click(janrain_capture_logout);
});';
  }

  if (isset($_SESSION['janrain_capture_password_recover']) && $_SESSION['janrain_capture_password_recover'] == TRUE) {
    $scripts['inline'][] = 'jQuery(function($) {
  $.fancybox({
    type: "iframe",
    href: "' . url('janrain_capture/profile', array('absolute' => TRUE, 'query' => array('method' => '_change_password'))) . '",
    padding: 0,
    scrolling: "no",
    autoScale: true,
    width: 666,
    autoDimensions: false
  });
});';
    $_SESSION['janrain_capture_password_recover'] = FALSE;
  }

  $final_scripts = module_invoke_all('janrain_capture_add_js', $scripts);
  $final_styles = module_invoke_all('janrain_capture_add_css', $styles);

  if (is_array($final_scripts) && !empty($final_scripts))
    $scripts = $final_scripts;
  if (is_array($final_styles) && !empty($final_styles))
    $styles = $final_styles;

  if (isset($scripts['module']) && is_array($scripts['module'])) {
    foreach ($scripts['module'] as $s) {
      drupal_add_js($s, array('type' => 'file', 'weight' => JS_DEFAULT, 'scope' => 'footer'));
    }
  }
  if (isset($scripts['inline']) && is_array($scripts['inline'])) {
    foreach ($scripts['inline'] as $s) {
      drupal_add_js($s, array('type' => 'inline', 'scope' => 'footer'));
    }
  }
  if (is_array($styles)) {
    foreach ($styles as $s) {
      drupal_add_css($s);
    }
  }
}

/**
 * Implements hook_page_build().
 */
function janrain_capture_ui_page_build(&$page) {
  $janrain_capture_main = variable_get('janrain_capture_main', array());
  $janrain_capture_optional = variable_get('janrain_capture_optional', array());

  $scripts = '<script src="https://'
    . (!empty($janrain_capture_optional['captureui_address']) ? $janrain_capture_optional['captureui_address'] : $janrain_capture_main['capture_address'])
    . '/cdn/javascripts/capture_client.js" type="text/javascript"></script>';
  if (!empty($janrain_capture_optional['capture_sso_address'])) {
    $scripts .= '<script src="https://' . $janrain_capture_optional['capture_sso_address'] . '/sso.js" type="text/javascript"></script>';
  }
  $page['page_bottom']['janrain_capture_ui'] = array(
    '#type' => 'markup',
    '#markup' => $scripts,
  );
}

/**
 * Implements hook_form_alter().
 */
function janrain_capture_ui_form_user_profile_form_alter(&$form, $form_state) {
  global $user;

  if ($user->uid == $form['#user']->uid) {
    $form['account'] = array(
      '#type' => 'fieldset',
      '#title' => t('My Account'),
      '#collapsible' => TRUE,
      '#collapsed' => FALSE
    );
    $form['account']['description'] = array(
      '#markup' => '<div class="form-item">
                    <a class="iframe fancy" href="' . url('janrain_capture/profile', array('absolute' => TRUE)) . '">' . t('Edit Profile') . '</a>
                </div>'
    );
  }
}

/**
 * Implements hook_menu_alter().
 */
function janrain_capture_ui_menu_alter(&$items) {
  $items['user/register']['access callback'] = 'user_access';
  $items['user/register']['access arguments'] = array('administer users');

  $items['user/password']['access callback'] = 'user_access';
  $items['user/password']['access arguments'] = array('administer users');
}

/**
 * Implements hook_block_info().
 */
function janrain_capture_ui_block_info() {
  return array(
    'janrain_capture' => array(
      'info' => t('Janrain Capture'),
    ),
  );
}

/**
 * Implements hook_block_view().
 */
function janrain_capture_ui_block_view($delta) {
  $janrain_capture_main = variable_get('janrain_capture_main', array());
  $janrain_capture_optional = variable_get('janrain_capture_optional', array());


  if (!empty($janrain_capture_main['capture_address']) && !empty($janrain_capture_main['capture_client_id'])) {
    $CAPTURE_LOGIN_URL = 'https://'
      . (!empty($janrain_capture_optional['captureui_address']) ? $janrain_capture_optional['captureui_address'] : $janrain_capture_main['capture_address'])
      . '/oauth/signin?response_type=code&flags=stay_in_window&recover_password_callback=closeRecoverPassword&redirect_uri='
      . urlencode(url('janrain_capture/oauth', array('absolute' => TRUE)))
      . '&client_id='
      . $janrain_capture_main['capture_client_id']
      . '&xd_receiver='
      . urlencode(url(NULL, array('absolute' => TRUE)) . drupal_get_path('module', 'janrain_capture') . '/xdcomm.html');
  }

  $content = array();

  switch ($delta) {
    case 'janrain_capture':
      $content['subject'] = t('Janrain Capture');
      $output = '';
      global $user;
      if ($user->uid) {
        if (!isset($_SESSION['janrain_capture_access_token'])) {
          $_SESSION['janrain_capture_access_token'] = FALSE;
        }
        $output .= $_SESSION['janrain_capture_access_token'] ? '<li><a class="iframe fancy" href="' . url('janrain_capture/profile', array('absolute' => TRUE)) . '">' . t('View / Edit Profile') . '</a></li>' : '';
        $output .= '<li><a href="' . url('user/logout') . '" onclick="janrain_capture_logout">' . t('Log out') . '</a></li>';
      }
      else {
        $output .= '<li><a class="iframe fancy" href="' . $CAPTURE_LOGIN_URL . '">' . t('Register / Sign In') . '</a></li>';
      }

      $content['content'] = '<ul class="menu"' . $output . '</ul>';
      break;
  }

  return $content;
}