<?php

/**
 * @file
 * This module implements UI elements for Janrain Capture
 *
 * @see http://www.janrain.com/products/capture
 */

/**
 * Implements hook_init().
 */
function janrain_capture_ui_init() {
  $js_css = array(
    'js' => array(
      'fancybox' => 'jquery.fancybox-1.3.4.pack.js',
    ),
    'css' => array(
      'fancybox' => 'jquery.fancybox-1.3.4.css',
    )
  );

  foreach ($js_css as $type => $files) {
    foreach ($files as $name => $filename) {
      // Find the location of the library file and add it using the appropriate
      // function, i.e. drupal_add_js or drupal_add_css.
      $full_path = janrain_capture_ui_get_library_path($name) . '/' . $filename;
      $drupal_add = sprintf('drupal_add_%s', $type);
      $drupal_add($full_path, array('every_page' => TRUE));
    }
  }
  // Finally, add the custom JavaScript.
  drupal_add_js(drupal_get_path('module', 'janrain_capture') . '/janrain_capture_ui.js', array('every_paage' => TRUE));
}

/**
 * Find the location of library JS and CSS files.
 */
function janrain_capture_ui_get_library_path($name) {
  $lib_paths = &drupal_static(__FUNCTION__, array());
  if (!isset($lib_paths[$name])) {
    $cid = 'janrain_capture_libraries';
    $cache = cache_get($cid);

    if (!empty($cache->data)) {
      $lib_paths = $cache->data;
      if (isset($lib_paths[$name])) {
        return $lib_paths[$name];
      }
    }

    // Use Libraries module, if available, to find the correct path.
    if (function_exists('libraries_get_path')) {
      $lib_path = libraries_get_path($name);
      if (!empty($lib_path)) {
        $lib_paths[$name] = $lib_path;
      }
    }

    // If we still haven't found a path, assume it's at sites/all/libraries
    if (!isset($lib_paths[$name])) {
      $lib_paths[$name] = 'sites/all/libraries/' . $name;
    }
    cache_set($cid, $lib_paths);
  }
  return $lib_paths[$name];
}

/**
 * Implements hook_form_FROM_ID_alter().
 */
function janrain_capture_ui_form_user_profile_form_alter(&$form, &$form_state) {
  global $user;
  $link = l(
    t('Edit Profile'),
    'janrain_capture/profile',
    array(
      'absolute' => TRUE,
      'attributes' => array(
        'class' => array('iframe', 'fancy', 'janrain_capture_anchor'),
      ),
    )
  );
  $markup = '<div class="form-item">' . $link . '</div>';
  if ($user->uid == $form['#user']->uid) {
    $form['account'] = array(
      '#type' => 'fieldset',
      '#title' => t('My Account'),
      '#collapsible' => TRUE,
      '#collapsed' => FALSE,
    );
    $form['account']['description'] = array(
      '#type' => 'markup',
      '#markup' => $markup,
    );
  }
}

/**
 * Implements hook_menu_alter().
 */
function janrain_capture_ui_menu_alter(&$items) {
  $items['user/register']['access callback'] = 'user_access';
  $items['user/register']['access arguments'] = array('administer users');

  $items['user/password']['access callback'] = 'user_access';
  $items['user/password']['access arguments'] = array('administer users');
}

/**
 * Implements hook_block_info().
 */
function janrain_capture_ui_block_info() {
  return array(
    'janrain_capture' => array(
      'info' => t('Janrain Capture'),
    ),
  );
}

/**
 * Implements hook_block_view().
 */
function janrain_capture_ui_block_view($delta) {
  $janrain_capture_optional = variable_get('janrain_capture_optional', array());
  switch ($delta) {
    case 'janrain_capture':
      global $user;
      $items = array();
      if ($user->uid) {
        $items[] = l(
          t('View / Edit Profile'),
          'janrain_capture/profile',
          array(
            'absolute' => TRUE,
            'attributes' => array(
              'class' => array('iframe', 'fancy', 'janrain_capture_anchor'),
            ),
          )
        );
        if ($janrain_capture_optional['capture_sso_address']) {
          $items[] = '<a href="javascript:CAPTURE.logout()">' . t('Log out') . '</a>';
        }
        else {
          $items[] = l(t('Log out'), 'user/logout');
        }
      }
      else {
        $items[] = l(
          t('Register / Sign in'),
          janrain_capture_url(),
          array(
            'attributes' => array(
              'class' => array(
                'iframe',
                'fancy',
                'janrain_capture_anchor',
                'janrain_capture_signin',
              ),
            ),
          )
        );
      }
      $block = array(
        'subject' => t('Janrain Capture'),
        'content' => theme('item_list', array('items' => $items)),
      );
      break;
  }

  return $block;
}
