<?php

/**
 * @file
 * This module implements UI elements for Janrain Capture
 *
 * @see http://www.janrain.com/products/capture
 */

/**
 * Implements hook_init().
 */
function janrain_capture_ui_init() {
  global $user;

  $janrain_capture_main = variable_get('janrain_capture_main', array());
  $janrain_capture_optional = variable_get('janrain_capture_optional', array());
  $janrain_capture_dependencies = variable_get('janrain_capture_dependencies', array());

  // Don't do anything if the module settings have not been configured.
  if (!isset($janrain_capture_main['capture_address'])
    || !isset($janrain_capture_main['capture_client_id'])
    || !isset($janrain_capture_main['capture_client_secret'])) {
    return;
  }
  $capture_sso_address = !empty($janrain_capture_optional['capture_sso_address'])
    ? $janrain_capture_optional['capture_sso_address'] : '';
  $capture_client_id = !empty($janrain_capture_main['capture_client_id'])
    ? $janrain_capture_main['capture_client_id'] : '';

  $path = isset($_GET['q']) ? $_GET['q'] : '<front>';
  $link = url($path, array('absolute' => TRUE));
  $uri_opts = array('query' => array('origin' => urlencode($link)), 'absolute' => TRUE);
  $settings = array(
    'janrainCapture' => array(
      'profile_sync_url' => url('janrain_capture/profile_sync', $uri_opts),
      'token_expired_url' => url('janrain_capture/token_expired'),
      'logout_url' => url('user/logout', array('absolute' => TRUE)),
    ),
  );
  if (!empty($capture_sso_address)) {
    $settings['janrainCapture']['sso_address'] = $capture_sso_address;
  }
  if (!empty($janrain_capture_optional['backplane_server'])
    && !empty($janrain_capture_optional['backplane_bus_name'])) {
    $settings['janrainCapture']['backplane_server'] = $janrain_capture_optional['backplane_server'];
    $settings['janrainCapture']['backplane_bus_name'] = $janrain_capture_optional['backplane_bus_name'];
  }
  drupal_add_js($settings, 'setting');

  $scripts = array(
    'module' => array(),
    'inline' => array(),
    'external' => array(),
  );
  $scripts['external'][] = 'https://'
    . (!empty($janrain_capture_optional['captureui_address'])
      ? $janrain_capture_optional['captureui_address']
      : $janrain_capture_main['capture_address'])
    . '/cdn/javascripts/capture_client.js';
  $scripts['module'][] = !empty($janrain_capture_dependencies['capture_json2'])
    ? $janrain_capture_dependencies['capture_json2']
    : 'sites/all/libraries/json2/json2.js';
  $scripts['module'][] = !empty($janrain_capture_dependencies['capture_fancy_js'])
    ? $janrain_capture_dependencies['capture_fancy_js']
    : 'sites/all/libraries/fancybox/jquery.fancybox-1.3.4.pack.js';
  $scripts['module'][] = url(NULL, array('absolute' => TRUE)) . drupal_get_path('module', 'janrain_capture') . '/janrain_capture_ui.js';

  $styles = array();
  $styles[] = !empty($janrain_capture_dependencies['capture_fancy_css'])
    ? $janrain_capture_dependencies['capture_fancy_css']
    : 'sites/all/libraries/fancybox/jquery.fancybox-1.3.4.css';

  if (!empty($capture_sso_address)) {
    $scripts['external'][] = "https://$capture_sso_address/sso.js";
    $scripts['inline'][] = 'JANRAIN.SSO.CAPTURE.check_login({
  sso_server: "https://' . $capture_sso_address . '",
  client_id: "' . $capture_client_id . '",
  redirect_uri: "' . url('janrain_capture/oauth', array('absolute' => TRUE)) . '",
  logout_uri: "' . url('user/logout', array('absolute' => TRUE)) . '",
  xd_receiver: "' . url(NULL, array('absolute' => TRUE)) . drupal_get_path('module', 'janrain_capture') . '/xdcomm.html"
});';
  }

  if (!empty($janrain_capture_optional['backplane_js_path'])) {
    $scripts['external'][] = $janrain_capture_optional['backplane_js_path'];
  }

  if (isset($_SESSION['janrain_capture_password_recover']) && $_SESSION['janrain_capture_password_recover'] == TRUE) {
    $scripts['inline'][] = 'jQuery(function($) {
  $.fancybox({
    type: "iframe",
    href: "' . url('janrain_capture/profile', array('absolute' => TRUE, 'query' => array('method' => '_change_password', 'callback' => 'CAPTURE.closeRecoverPassword'))) . '",
    padding: 0,
    scrolling: "no",
    autoScale: true,
    width: 666,
    autoDimensions: false
  });
});';
    $_SESSION['janrain_capture_password_recover'] = FALSE;
  }

  if (isset($scripts['external']) && is_array($scripts['external'])) {
    foreach ($scripts['external'] as $s) {
      drupal_add_js($s, array('type' => 'external'));
    }
  }
  if (isset($scripts['module']) && is_array($scripts['module'])) {
    foreach ($scripts['module'] as $s) {
      drupal_add_js($s, array('type' => 'file'));
    }
  }
  if (isset($scripts['inline']) && is_array($scripts['inline'])) {
    foreach ($scripts['inline'] as $s) {
      drupal_add_js($s, array('type' => 'inline'));
    }
  }
  if (is_array($styles)) {
    foreach ($styles as $s) {
      drupal_add_css($s);
    }
  }
}

/**
 * Implements hook_form_FROM_ID_alter().
 */
function janrain_capture_ui_form_user_profile_form_alter(&$form, &$form_state) {
  global $user;
  $link = l(
    t('Edit Profile'),
    'janrain_capture/profile',
    array(
      'absolute' => TRUE,
      'attributes' => array(
        'class' => array('iframe', 'fancy', 'janrain_capture_anchor'),
      ),
    )
  );
  $markup = '<div class="form-item">' . $link . '</div>';
  if ($user->uid == $form['#user']->uid) {
    $form['account'] = array(
      '#type' => 'fieldset',
      '#title' => t('My Account'),
      '#collapsible' => TRUE,
      '#collapsed' => FALSE,
    );
    $form['account']['description'] = array(
      '#type' => 'markup',
      '#markup' => $markup,
    );
  }
}

/**
 * Implements hook_menu_alter().
 */
function janrain_capture_ui_menu_alter(&$items) {
  $items['user/register']['access callback'] = 'user_access';
  $items['user/register']['access arguments'] = array('administer users');

  $items['user/password']['access callback'] = 'user_access';
  $items['user/password']['access arguments'] = array('administer users');
}

/**
 * Implements hook_block_info().
 */
function janrain_capture_ui_block_info() {
  return array(
    'janrain_capture' => array(
      'info' => t('Janrain Capture'),
    ),
  );
}

/**
 * Implements hook_block_view().
 */
function janrain_capture_ui_block_view($delta) {
  $janrain_capture_optional = variable_get('janrain_capture_optional', array());
  switch ($delta) {
    case 'janrain_capture':
      global $user;
      $items = array();
      if ($user->uid) {
        $items[] = l(
          t('View / Edit Profile'),
          'janrain_capture/profile',
          array(
            'absolute' => TRUE,
            'attributes' => array(
              'class' => array('iframe', 'fancy', 'janrain_capture_anchor'),
            ),
          )
        );
        if ($janrain_capture_optional['capture_sso_address']) {
          $items[] = '<a href="javascript:CAPTURE.logout()">' . t('Log out') . '</a>';
        }
        else {
          $items[] = l(t('Log out'), 'user/logout');
        }
      }
      else {
        $items[] = l(
          t('Register / Sign in'),
          janrain_capture_url(),
          array(
            'attributes' => array(
              'class' => array(
                'iframe',
                'fancy',
                'janrain_capture_anchor',
                'janrain_capture_signin',
              ),
            ),
          )
        );
      }
      $block = array(
        'subject' => t('Janrain Capture'),
        'content' => theme('item_list', array('items' => $items)),
      );
      break;
  }

  return $block;
}
