<?php

/**
 * @file
 * This module implements authentication endpoints for Janrain Capture.
 *
 * @see http://www.janrain.com/products/capture
 */

/**
 * Implements hook_init().
 */
function janrain_capture_init() {

  $janrain_capture_main = variable_get('janrain_capture_main', array());
  $janrain_capture_optional = variable_get('janrain_capture_optional', array());

  // Don't do anything if the module settings have not been configured.
  if (!isset($janrain_capture_main['capture_address'])
    || !isset($janrain_capture_main['capture_client_id'])
    || !isset($janrain_capture_main['capture_client_secret'])) {
    return;
  }
  $capture_sso_address = !empty($janrain_capture_optional['capture_sso_address'])
    ? $janrain_capture_optional['capture_sso_address'] : '';
  $capture_client_id = !empty($janrain_capture_main['capture_client_id'])
    ? $janrain_capture_main['capture_client_id'] : '';

  $uri_opts = array('absolute' => TRUE);
  if ($_GET['q']) {
    $uri_opts['query'] = array('destination' => $_GET['q']);
  }
  $settings = array(
    'janrainCapture' => array(
      'profile_sync_url' => url('janrain_capture/profile_sync', $uri_opts),
      'token_expired_url' => url('janrain_capture/token_expired/' . drupal_get_token('janrain_capture_token_expired')),
      'logout_url' => url('user/logout', array('absolute' => TRUE)),
    ),
  );
  if (!empty($capture_sso_address)) {
    $settings['janrainCapture']['sso_address'] = $capture_sso_address;
  }
  if (!empty($janrain_capture_optional['backplane_server'])
    && !empty($janrain_capture_optional['backplane_bus_name'])) {
    $settings['janrainCapture']['backplane_server'] = $janrain_capture_optional['backplane_server'];
    $settings['janrainCapture']['backplane_bus_name'] = $janrain_capture_optional['backplane_bus_name'];
  }
  drupal_add_js($settings, 'setting');

  $scripts = array(
    'file' => array(),
    'inline' => array(),
    'external' => array(),
  );
  $scripts['file'][] = drupal_get_path('module', 'janrain_capture') . '/janrain_capture.js';
  $scripts['external'][] = 'https://'
    . (!empty($janrain_capture_optional['captureui_address'])
      ? $janrain_capture_optional['captureui_address']
      : $janrain_capture_main['capture_address'])
    . '/cdn/javascripts/capture_client.js';


  if (!empty($capture_sso_address)) {
    $scripts['external'][] = "https://$capture_sso_address/sso.js";
    $scripts['inline'][] = 'JANRAIN.SSO.CAPTURE.check_login({
  sso_server: "https://' . $capture_sso_address . '",
  client_id: "' . $capture_client_id . '",
  redirect_uri: "' . url('janrain_capture/oauth', array('absolute' => TRUE)) . '",
  logout_uri: "' . url('user/logout', array('absolute' => TRUE)) . '",
  xd_receiver: "' . url(NULL, array('absolute' => TRUE)) . drupal_get_path('module', 'janrain_capture') . '/xdcomm.html"
});';
  }

  if (!empty($janrain_capture_optional['backplane_js_path'])) {
    $scripts['external'][] = $janrain_capture_optional['backplane_js_path'];
  }

  if (isset($_SESSION['janrain_capture_password_recover']) && $_SESSION['janrain_capture_password_recover'] == TRUE) {
    $url = url('janrain_capture/profile', array(
      'absolute' => TRUE,
      'query' => array(
        'method' => '_change_password',
        'callback' => 'Drupal.janrainCapture.closeRecoverPassword',
      ),
    ));
    $scripts['inline'][] = 'jQuery(function($) {Drupal.janrainCapture.passwordRecover(' . $url .')});';
    $_SESSION['janrain_capture_password_recover'] = FALSE;
  }

  foreach (array_keys($scripts) as $type) {
    foreach ($scripts[$type] as $s) {
      drupal_add_js($s, array('type' => $type));
    }
  }
}

/**
 * Implements hook_menu().
 */
function janrain_capture_menu() {

  $items['janrain_capture/oauth'] = array(
    'title' => 'Capture Oauth Receiver',
    'page callback' => 'janrain_capture_oauth',
    'access callback' => 'user_is_anonymous',
    'type' => MENU_CALLBACK,
    'file' => 'janrain_capture.pages.inc',
  );

  $items['janrain_capture/profile'] = array(
    'title' => 'Capture Profile',
    'page callback' => 'janrain_capture_profile',
    'access callback' => 'user_is_logged_in',
    'type' => MENU_CALLBACK,
    'file' => 'janrain_capture.pages.inc',
  );

  $items['janrain_capture/profile_sync'] = array(
    'title' => 'Capture Profile Receiver',
    'page callback' => 'janrain_capture_profile_sync',
    'access callback' => 'user_is_logged_in',
    'type' => MENU_CALLBACK,
    'file' => 'janrain_capture.pages.inc',
  );

  $items['janrain_capture/resend_verification_email'] = array(
    'title' => 'Capture Verification Email Resent',
    'page callback' => 'janrain_capture_resend_verification_email',
    'access callback' => TRUE,
    'type' => MENU_CALLBACK,
    'file' => 'janrain_capture.pages.inc',
  );

  $items['admin/config/people/janrain_capture'] = array(
    'title' => 'Janrain Capture',
    'description' => 'Configure settings for Janrain Capture module.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('janrain_capture_settings'),
    'access arguments' => array('administer site configuration'),
    'file' => 'janrain_capture.admin.inc',
  );

  $items['janrain_capture/token_expired/%'] = array(
    'title' => 'Capture Token Expired',
    'page callback' => 'janrain_capture_token_expired',
    'page arguments' => array(2),
    'access callback' => 'user_is_logged_in',
    'type' => MENU_CALLBACK,
    'file' => 'janrain_capture.pages.inc',
  );

  return $items;
}

/**
 * Returns the full URL of a specified CaptureUI screen
 *
 * @param array $options
 *   An associative array of options to use in constructing the URL
 *
 * @return string
 *   The full URL string of the Capture URL screen being requested
 */
function janrain_capture_url($options = NULL) {
  $janrain_capture_main = variable_get('janrain_capture_main', array());
  $janrain_capture_optional = variable_get('janrain_capture_optional', array());
  if (!empty($janrain_capture_main['capture_address'])
    && !empty($janrain_capture_main['capture_client_id'])) {

    $required = array(
      'redirect_uri' => url('janrain_capture/oauth', array('absolute' => TRUE)),
      'xd_receiver' => url(NULL, array('absolute' => TRUE)) . drupal_get_path('module', 'janrain_capture') . '/xdcomm.html',
      'client_id' => $janrain_capture_main['capture_client_id'],
    );

    if (!$options || strpos($options['action'], 'profile') !== 0) {
      if (!$options) {
        $options = array();
      }
      $defaults = array(
        'action' => 'signin',
        'recover_password_callback' => 'Drupal.janrainCapture.closeRecoverPassword',
        'response_type' => 'code',
      );
    }
    else {
      $defaults = array(
        'callback' => 'Drupal.janrainCapture.closeProfileEditor',
      );
    }
    $args = array_merge($required, $defaults, $options);
    $action = $args['action'];
    unset($args['action']);

    $url = 'https://'
      . (!empty($janrain_capture_optional['captureui_address']) ? $janrain_capture_optional['captureui_address'] : $janrain_capture_main['capture_address'])
      . '/oauth/' . $action . '?' . http_build_query($args, '', '&');
  }
  else {
    $url = '';
  }
  return $url;
}
